export class TableNames {
    static users = "users"
    static device_tokens = "device_tokens"
    static admin = "admin"
    // Legacy + canonical aliases (different modules referenced both styles)
    static foodCategory = "food_categories"
    static product = "products"
    static restaurants = "restaurants"
    static addon = "addons"
    static productAddon = "product_addons"
    static productSize = "product_sizes"
    static productSpecification = "product_specifications"
    static cuisine = "cuisines"
    static city = "cities"
    static deliverymen = "deliverymen"
    static favorites = "favorites"
    static cart = "cart"
    static coupons = "coupons"
    static offers = "offers"
    static offerProducts = "offer_products"
}